// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/solicitante": {
            "get": {
                "description": "Show a solicitante",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solicitante"
                ],
                "summary": "Show solicitante",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Solicitante identification",
                        "name": "cnpj",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ShowSolicitanteResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new solicitante",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solicitante"
                ],
                "summary": "Create solicitante",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateSolicitanteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.CreateSolicitanteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a solicitante data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solicitante"
                ],
                "summary": "Update solicitante",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateSolicitanteRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Solicitante identification",
                        "name": "cnpj",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateSolicitanteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/solicitantes": {
            "get": {
                "description": "List all solicitantes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solicitante"
                ],
                "summary": "List solicitante",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ListSolicitanteResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.CreateSolicitanteRequest": {
            "type": "object",
            "properties": {
                "cep": {
                    "type": "string"
                },
                "cidade": {
                    "type": "string"
                },
                "cnpj": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "nome_fantasia": {
                    "type": "string"
                },
                "numero": {
                    "type": "string"
                },
                "rua": {
                    "type": "string"
                }
            }
        },
        "handler.CreateSolicitanteResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/schemas.Solicitante"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.ListSolicitanteResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.Solicitante"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.ShowSolicitanteResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/schemas.Solicitante"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.UpdateSolicitanteRequest": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean"
                },
                "cep": {
                    "type": "string"
                },
                "cidade": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "nome_fantasia": {
                    "type": "string"
                },
                "numero": {
                    "type": "string"
                },
                "rua": {
                    "type": "string"
                }
            }
        },
        "handler.UpdateSolicitanteResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/schemas.Solicitante"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "schemas.Solicitante": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean"
                },
                "cep": {
                    "type": "string"
                },
                "cidade": {
                    "type": "string"
                },
                "cnpj": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "nomeFantasia": {
                    "type": "string"
                },
                "numero": {
                    "type": "string"
                },
                "rua": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
